const BookingActionType = {
    BOOKING_REQUEST: 'BOOKING_REQUEST',
    BOOKING_REQUEST_SUCCESS: 'BOOKING_REQUEST_SUCCESS',
    BOOKING_REQUEST_FAILURE: 'BOOKING_REQUEST_FAILURE',
    SCHEDULE_REQUEST: 'SCHEDULE_REQUEST',
    SCHEDULE_REQUEST_SUCCESS: 'SCHEDULE_REQUEST_SUCCESS',
    SCHEDULE_REQUEST_FAILURE: 'SCHEDULE_REQUEST_FAILURE',
    TOPIC_REQUEST: 'TOPIC_REQUEST',
    TOPIC_REQUEST_SUCCESS: 'TOPIC_REQUEST_SUCCESS',
    TOPIC_REQUEST_FAIURE: 'TOPIC_REQUEST_FAIURE',

    DETAIL_CLASS_REQUEST: 'DETAIL_CLASS_REQUEST',
    DETAIL_CLASS_REQUEST_SUCCESS: 'DETAIL_CLASS_REQUEST_SUCCESS',
    DETAIL_CLASS_REQUEST_FAILURE: 'DETAIL_CLASS_REQUEST_FAILURE',

    BOOKING_RESET: 'BOOKING_RESET',

    //
    USER_REQUEST:"USER_REQUEST",
    USER_REQUEST_SUCCESS:"USER_REQUEST_SUCCESS",
    USER_REQUEST_FAILURE:"USER_REQUEST_FAILURE",
}

export default BookingActionType;