const NotificationActionType = {
    NOTI_REQUEST: "NOTI_REQUEST",
    NOTI_REQUEST_SUCCESS: "NOTI_REQUEST_SUCCESS",
    NOTI_REQUEST_FAILURE: "NOTI_REQUEST_FAILURE",

    MARK_READ_REQUEST: "MARK_READ_REQUEST",
    MARK_READ_REQUEST_SUCCESS: "MARK_READ_REQUEST_SUCCESS",
    MARK_READ_REQUEST_FAILURE: "MARK_READ_REQUEST_FAILURE",

    READ_NOTIFICATION_REQUEST: "READ_NOTIFICATION_REQUEST",
    READ_NOTIFICATION_REQUEST_SUCCESS: "READ_NOTIFICATION_REQUEST_SUCCESS",
    READ_NOTIFICATION_REQUEST_FAILURE: "READ_NOTIFICATION_REQUEST_FAILURE",
    READ_NOTIFICATION_RESET: "READ_NOTIFICATION_RESET"


}

export default NotificationActionType;