const SecurityActionType = {
    SECURITY_LOGIN_REQUEST: "SECURITY_LOGIN_REQUEST",
    SECURITY_LOGIN_SUCCESS: "SECURITY_LOGIN_SUCCESS",
    SECURITY_LOGIN_FAILURE: "SECURITY_LOGIN_FAILURE",
    SECURITY_LOGIN_RESET: 'SECURITY_LOGIN_RESET',
    SECURITY_LOAD_SUCCESS: 'SECURITY_LOAD_SUCCESS',
    SECURITY_LOGOUT_REQUEST: 'SECURITY_LOGOUT_REQUEST',
    SECURITY_LOGOUT_SUCCESS: 'SECURITY_LOGOUT_SUCCESS',
    SECURITY_LOGOUT_FAILURE: 'SECURITY_LOGOUT_FAILURE',
    SECURITY_CHECK_TOKEN_REQUEST: 'SECURITY_CHECK_TOKEN_REQUEST',
    SECURITY_CHECK_TOKEN_SUCCESS: 'SECURITY_CHECK_TOKEN_SUCCESS',
    SECURITY_CHECK_TOKEN_FAILURE: 'SECURITY_CHECK_TOKEN_FAILURE',
}

export default SecurityActionType;