const UserActionType = {
    USER_REQUEST: 'USER_REQUEST',
    USER_REQUEST_SUCCESS: 'USER_REQUEST_SUCCESS',
    USER_REQUEST_FAILURE: 'USER_REQUEST_FAILURE',
    USER_RESET: 'USER_RESET',
    USER_FORM_REQUEST: 'USER_FORM_REQUEST',
    USER_FORM_REQUEST_SUCCESS: 'USER_FORM_REQUEST_SUCCESS',
    USER_FORM_REQUEST_FAILURE: 'USER_FORM_REQUEST_FAILURE',
    USER_FORM_RESET: 'USER_FORM_RESET',
    UPLOAD_IMAGE_REQUEST: "UPLOAD_IMAGE_REQUEST",
    UPLOAD_IMAGE_REQUEST_SUCCESS: "UPLOAD_IMAGE_REQUEST_SUCCESS",
    UPLOAD_IMAGE_REQUEST_FAILURE: "UPLOAD_IMAGE_REQUEST_FAILURE",
    UPLOAD_IMAGE_RESET: "UPLOAD_IMAGE_RESET"
}

export default UserActionType;