const ViewUserClassesActionType = {
    USER_CLASSES_REQUEST: "USER_CLASSES_REQUEST",
    USER_CLASSES_REQUEST_SUCCESS: 'USER_CLASSES_REQUEST_SUCCESS',
    USER_CLASSES_REQUEST_FAILURE: 'USER_CLASSES_REQUEST_FAILURE',

    CLASS_REQUEST: 'CLASS_REQUEST',
    CLASS_REQUEST_SUCCESS: 'CLASS_REQUEST_SUCCESS',
    CLASS_REQUEST_FAILURE: 'CLASS_REQUEST_SUCCESS',
    CLASS_RESET: 'CLASS_RESET',

    CLASS_REVIEW_REQUEST: 'CLASS_REVIEW_REQUEST',
    CLASS_REVIEW_REQUEST_SUCCESS: 'CLASS_REVIEW_REQUEST_SUCCESS',
    CLASS_REVIEW_REQUEST_FAILURE: 'CLASS_REVIEW_REQUEST_SUCCESS',
    CLASS_REVIEW_RESET: 'CLASS_REVIEW_RESET',

    DETAIL_CLASS_REQUEST: 'DETAIL_CLASS_REQUEST',
    DETAIL_CLASS_REQUEST_SUCCESS: 'DETAIL_CLASS_REQUEST_SUCCESS',
    DETAIL_CLASS_REQUEST_FAILURE: 'DETAIL_CLASS_REQUEST_FAILURE',
    DETAIL_CLASS_RESET: 'DETAIL_CLASS_RESET'
}

export default ViewUserClassesActionType;