const LocationActionType = {
    LOCATION_LIST_REQUEST: "LOCATION_LIST_REQUEST",
    LOCATION_LIST_REQUEST_SUCCESS: "LOCATION_LIST_REQUEST_SUCCESS",
    LOCATION_LIST_REQUEST_FAILURE: "LOCATION_LIST_REQUEST_FAILURE",
    LOCATION_LIST_RESET: "LOCATION_LIST_RESET",
    SCHEDULE_REQUEST: "SCHEDULE_REQUEST",
    SCHEDULE_REQUEST_SUCCESS: "SCHEDULE_REQUEST_SUCCESS",
    SCHEDULE_REQUEST_FAILURE: "SCHEDULE_REQUEST_FAILURE",
    SET_SCHEDULE_REQUEST: "SET_SCHEDULE_REQUEST",
    SET_SCHEDULE_REQUEST_SUCCESS: "SET_SCHEDULE_REQUEST_SUCCESS",
    SET_SCHEDULE_REQUEST_FAILURE: "SET_SCHEDULE_REQUEST_FAILURE",
    SET_SCHEDULE_RESET: "SET_SCHEDULE_RESET",
}

export default LocationActionType;