const TopicActionType = {
    TOPIC_LIST_REQUEST: "TOPIC_LIST_REQUEST",
    TOPIC_LIST_REQUEST_SUCCESS: "TOPIC_LIST_REQUEST_SUCCESS",
    TOPIC_LIST_REQUEST_FAILURE: "TOPIC_LIST_REQUEST_FAILURE",
    TOPIC_LIST_RESET: "TOPIC_LIST_RESET",
}

export default TopicActionType;