const TeacherActionType = {
    TEACHER_LIST_REQUEST: "TEACHER_LIST_REQUEST",
    TEACHER_LIST_REQUEST_SUCCESS: "TEACHER_LIST_REQUEST_SUCCESS",
    TEACHER_LIST_REQUEST_FAILURE: "TEACHER_LIST_REQUEST_FAILURE",
    TEACHER_LIST_RESET: "TEACHER_LIST_RESET"
}

export default TeacherActionType;